config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :events do
    patch 'event_over', to: 'tickets#event_over', as: :event_over
    resources :tickets, only: %i[create index]
    patch 'tickets/:id/mark_as_cancelled', to: 'tickets#mark_as_cancelled', as: :mark_as_cancelled
    patch 'tickets/:id/mark_as_showed', to: 'tickets#mark_as_showed', as: :mark_as_showed
    patch 'tickets/:id/mark_as_attendee', to: 'tickets#mark_as_attendee', as: :mark_as_attendee
  end

  resources :tickets, only: %i[edit update show]

  resources :users, only: %i[new create show edit update] do
    resources :events, only: %i[new create]
    patch 'switch_to_organizer', to: 'users#switch_to_organizer', as: :switch_to_organizer
    patch 'switch_to_attendee', to: 'users#switch_to_attendee', as: :switch_to_attendee
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  get 'pages/sign_up_details', to: 'pages#sign_up_details', as: :sign_up_details
  get 'dashboard', to: 'dashboards#index', as: :dashboard
  root to: 'pages#home'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_modal_template.html.erb
<!-- Button trigger modal -->
<button type="button" id="paymentModal" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" style="display: none">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="row py-4">
            <div class="col-md-3"><%#= image_tag @order.teddy.photo_url, width: '100%' %></div>
            <div class="col">
              <h1>Checkout summary</h1>
              <p>Purchase of <strong><%= event.title %></strong> for <strong><%= humanized_money_with_symbol event.stake %></strong></p>
              <button id="pay" class="btn btn-primary">Pay</button>
              <script src="https://js.stripe.com/v3/"></script>
              <script>
                const paymentButton = document.getElementById('pay');
                paymentButton.addEventListener('click', () => {
                  const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
                  stripe.redirectToCheckout({
                    sessionId: '<%= event.orders.where(user_id: current_user.id).checkout_session_id %>'
                  });
                });
              </script>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="interactive_bar">

  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon navnav">
    <div class="">
    <ul class="nav navbar-nav navbar-left">

     <li>
    <%= link_to root_path, class: "navbar-brand " do %>
      <%= image_tag "https://i.imgur.com/KsOrt0x.png" %>
   <% end %>
     </li>

    <li>
    <%= link_to events_path, class: "login_hover #{controller.controller_name == "events" ? "active_nav" : "nothing"} " do %>
      <span> EVENTS CATALOGUE </span>

    <% end %>
     </li>

     <li>
    <%# if @user %>
      <%= link_to dashboard_path, class: "login_hover  #{controller.controller_name == "dashboards" ? "active_nav" : "nothing"}" do %>
        <span> MY DASHBOARD </span>
      <% end %>
    <%# end %>
     </li>
    </ul>
    </div>
    <div class="btn_nav">
      <% if !current_user %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to new_user_registration_path, class: "login_hover" do %>
          <i class="fas fa-user-plus"></i>
          <span> SIGNUP </span>
        <% end %></li>
        <li><%= link_to new_user_session_path, class: "login_hover" do %>
          <i class="fas fa-sign-in-alt"></i>
          <span> LOGIN </span>
        <% end %></li>
      </ul>
      <% end %>
    </div>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
            <% if current_user&.avatar.attached? %>
              <% if current_user.organizer? %>
              <li class="login_hover current-name"> <%= current_user.organizer_name %></li>
              <% else %>
              <li class="login_hover current-name"> <%= current_user.first_name %> <%= current_user.last_name %></li>
              <% end %>
          <!--   <div class="current-name"><%=  current_user.user_type %></div> -->
          <li class="nav-item dropdown" class= "avatar dropdown-toggle" id= "navbarDropdown" data-toggle= "dropdown" aria-haspopup="true", aria-expanded="false" style="background-image: url('<%= cl_image_path current_user.avatar.key %>')">
              <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
          <li class="nav-item dropdown" class= "avatar dropdown-toggle" id= "navbarDropdown" data-toggle= "dropdown" aria-haspopup="true", aria-expanded="false">

              <div class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                XX
              </div>

            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
              <% if current_user.attendee? %>
                <%= link_to 'Switch to Organizer', user_switch_to_organizer_path(current_user), method: :patch, class: "dropdown-item" %>
              <% elsif current_user.organizer? %>
                  <%= link_to 'Switch to Attendee', user_switch_to_attendee_path(current_user), method: :patch, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

</div>
<script>
  document.querySelectorAll(".dropdown-item").forEach((div) => {
    div.addEventListener("click", (e) => {
      console.log(e.target)
      window.location = e.target.href
    })

  })
</script>