config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :events do
    patch 'event_over', to: 'tickets#event_over', as: :event_over
    resources :tickets, only: %i[create index]
    patch 'tickets/:id/mark_as_cancelled', to: 'tickets#mark_as_cancelled', as: :mark_as_cancelled
    patch 'tickets/:id/mark_as_showed', to: 'tickets#mark_as_showed', as: :mark_as_showed
    patch 'tickets/:id/mark_as_attendee', to: 'tickets#mark_as_attendee', as: :mark_as_attendee
  end

  resources :tickets, only: %i[edit update show]

  resources :users, only: %i[new create show edit update] do
    resources :events, only: %i[new create]
    patch 'switch_to_organizer', to: 'users#switch_to_organizer', as: :switch_to_organizer
    patch 'switch_to_attendee', to: 'users#switch_to_attendee', as: :switch_to_attendee
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  get 'pages/sign_up_details', to: 'pages#sign_up_details', as: :sign_up_details
  get 'dashboard', to: 'dashboards#index', as: :dashboard
  root to: 'pages#home'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :tickets, dependent: :destroy
  has_many :users, through: :tickets
  has_many :orders, dependent: :destroy
  has_one_attached :photo

  validates :title, presence: true
  validates :location, presence: true
  validates :description, presence: true
  validates :photo, presence: true
  validates :food, presence: true
  validates :drink, presence: true
  validates :number_max_of_attendees, presence: true
  validates :stake, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true

  monetize :stake_cents

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def future?
    start_time > DateTime.current.to_date
  end

  def close!
    self.status = 'Closed'
    save!
  end

  def closed?
    self.status == 'Closed'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
    @search = params["search"]
    if @search.present?
      @title = @search["title"]
      @events = Event.where("title ILIKE ?", "%#{@title}%")
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to event_path(@event)
    else
      render 'new'
    end
  end

  def show
    @user = current_user
    @ticket = @event.tickets.find_by(user: @user)
    @available_tickets = @event.tickets.select { |x| x.attendee? || x.showup? }.size
    @stake_earned = stake_earned
  end

  def stake_earned
     absent_people = @event.tickets.select { |ticket| ticket.attendee? }.size
     stake_value = @event.stake
     money_before_fee = absent_people * stake_value
     money_after_fee = money_before_fee - (money_before_fee * 0.3)
     return money_after_fee
  end


  def edit
  end

  def update
    @event.update(event_params)
    if @event.save
      redirect_to event_path(@event)
    else
      render 'new'
    end
  end

  def destroy
    @event.destroy
    redirect_to event_path(event)
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :location, :photo, :food,
     :drink, :number_max_of_attendees, :stake, :start_time, :end_time, :user_id)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/views/events/_countdown.html.erb
<!-- Display the countdown timer in an element -->
<p id="demo"></p>

<script>
// Set the date we're counting down to
var countDownDate = new Date('<%= @event.start_time %>').getTime();

// Update the count down every 1 second
var x = setInterval(function() {

  // Get today's date and time
  var now = new Date().getTime();

  // Find the distance between now and the count down date
  var distance = countDownDate - now;

  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

  // Display the result in the element with id="demo"
  document.getElementById("demo").innerHTML = "Starts in: " + days + " Days and " + hours + " Hours"

  // + seconds + " seconds "
  // If the count down is finished, write some text
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML = "EXPIRED";
  }
}, 1000);
</script>

app/views/events/_event_card.html.erb
<div class="mb-5 card" style="<%= "filter: saturate(0%);"  if event.start_time.past?  %>">
  <%= link_to event_path(event), class: 'special' do %>
    <div class="card-trip">
        <% if event.photo.attached? %>
          <%= cl_image_tag event.photo.key %>
        <% end %>
      <div class="card-trip-infos">
        <div class="details-trip">
          <p><%= event.start_time.strftime("%a, %d %b %Y") %> | <%= event.start_time.to_s[-12..-8] %> <i class="fas fa-arrow-right"></i> <%= event.end_time.to_s[-12..-8]%></p>
          <div class="details-trip-details">
            <h2 style="text-align: left;"><%= event.title %></h2>
            <p><%= event.user.organizer_name %></p>
          </div>
          <p><i class="fas fa-map-marker-alt"></i>
            <% if event.location.length > 42 %>
              <%= event.location[0..42] %> ...</p>
            <% else %>
              <%= event.location %>
            <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/events/_event_form.html.erb
<div class="container-form">

  <%= simple_form_for @event do |f| %>
    <%= f.input :title, label: 'Title', required: true, error: 'Adding a title is mandatory'%>
    <%= f.input :description, label: 'Description', required: true, error: 'Adding a description is mandatory' %>
    <%= f.input :location, label: 'Event location', required: true, error: 'Adding a location is mandatory' %>
    <%= f.input :photo, as: :file, required: true %>
    <div class="flex-container">
      <%= f.input :food, as: :select,
        collection: ["None", "Free", "Paid"], required: true, error: 'Please indicate whether food will be offered at the event'%>
      <%= f.input :drink, as: :select,
        collection: ["None", "Free", "Paid"], required: true, error: 'Please indicate whether drinks will be offered at the event' %>
    </div>

    <%= f.input :number_max_of_attendees, required: true, label: 'Maximum number of attendees', error: 'number_max_of_attendees error' %> <i class="far fa-question-circle info-popup" data-toggle="tooltip" data-placement="top" title="The stake is your commitment to the event; if you do not show up, the stake sum is withdrawn from your card. When your attendance is recorded at the event, the sum is not withdrawn from your card. If you cancel 5 days before the event, the stake amount is not withdrawn from your card."></i>
    <%= f.input :stake, label: 'Stake', required: true, error: 'Please provide a stake sum as an integer' %>
    <%= f.input :start_time, label: 'Start time', required: true, error: 'Selecting a start time for the event is mandatory' %>
    <%= f.input :end_time, label: 'End time', required: true, error: 'Selecting an end time for the event is mandatory' %>

    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/events/_search_bar.html.erb
<div class="container my-5 search-form">
  <div class="title">
  <div class="hz">
    <%= simple_form_for :search, url: events_path, method: "GET", html: { class: 'form-inline' } do |f| %>
        <%= f.input :title, required: false, input_html: {value: ""}, label: false %>
        <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="container_form">
  <div class="create_event_title">
  <h2>Update event details</h2>
  </div>
  <div class="container-form">
    <%= simple_form_for @event do |f| %>
      <%= f.input :title, label: 'Title', required: true, error: 'Adding a title is mandatory'%>
      <%= f.input :description, label: 'Description',required: true, error: 'Adding a description is mandatory' %>
      <%= f.input :location, label: 'Event location', required: true, error: 'Adding a location is mandatory' %>
      <%= f.input :photo, as: :file %>
      <div class="flex-container">
        <%= f.input :food,
          collection: ["None", "Free", "Paid"], required: true, selected: (@event.food ||'None'), error: 'Please indicate whether food will be offered at the event'%>
        <%= f.input :drink,
          collection: ["None", "Free", "Paid"], required: true, selected: (@event.drink ||'None'), error: 'Please indicate whether drinks will be offered at the event' %>
      </div>

      <%= f.input :number_max_of_attendees, label: 'Maximum number of attendees', required: true, error: 'number_max_of_attendees error' %>
      <%= f.input :start_time, label: 'Start time', required: true, error: 'Selecting a start time for the event is mandatory' %>
      <%= f.input :end_time, label: 'End time', required: true, error: 'Selecting an end time for the event is mandatory' %>

      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">
  <%= render 'search_bar' %>
  <div class="row">
    <% @events.select { |event| event.start_time.to_date > DateTime.current.to_date }.each do |event| %>
      <div class="home-cards col-sm-4">
        <%= render "events/event_card", event: event %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="container_form">
  <div class="create_event_title">
  <h2>Create a new Event</h2>
  </div>
  <%= render "event_form" %>
</div>
</div>

app/views/events/show.html.erb
<div class="container shadow-container">
  <div class="top-line">
    <div class="event_details_image " style= "background-image: url(<%= cl_image_path @event.photo.key %>);">
      <%#= cl_image_tag @event.photo.key %>
    </div>
    <% if @event.future? && !@event.closed? %>
      <div class="description">
        <p> <%= @event.start_time.strftime("%a, %d %b %Y") %>
        <div class="title">
          <p><%= @event.title %></p>
        </div>
        <p> by <%= @event.user.organizer_name %></p>
        <div class="stake-info">
          <p> Stake: <%= @event.stake %> € <i class="far fa-question-circle info-popup" data-toggle="tooltip" data-placement="top" title="The stake is your commitment to the event; if you do not show up, the stake sum is withdrawn from your card. When your attendance is recorded at the event, the sum is not withdrawn from your card. If you cancel 5 days before the event, the stake amount is not withdrawn from your card."></i> </p>
        </div>
        <% if !@user %>
          <%= link_to 'Login', new_user_session_path(), class: 'btn btn-primary' %>
        <% elsif @ticket.present? && @ticket.attendee? %>
          <div class="button-and-text">
            <div>
              <%= link_to 'Cancel', event_mark_as_cancelled_path(@event, @ticket), class: 'btn btn-danger', method: :patch, data: { confirm: 'Are you sure to delete your ticket ?' } %>
            </div>
            <div class="countdown">
              You have a ticket for this event <i class="fas fa-check"></i>
            </div>
          </div>
        <% elsif current_user.attendee? && (@ticket.nil? || (!@ticket.attendee? && !@ticket.showup?)) %>
          <div class="button-and-text">
            <div>
              <%= form_tag orders_path do %>
                <%= hidden_field_tag 'event_id', @event.id %>
                <%= submit_tag 'Attend', class: 'btn btn-primary' %>
              <% end %>
            </div>
            <div class="countdown">
              <%= render 'countdown' %>
            </div>
          </div>
        <% end %>

        <% if !@user %>
        <% elsif @user.organizer? && !@event.closed? %>
          <div class="my-5">
            <% if current_user.organizer? && current_user.organized_events.include?(@event) %>
              <%= link_to "Edit the event", edit_event_path(@event), class: 'btn btn-primary' %>
              <%= link_to "Manage attendees", event_tickets_path(@event), class: 'btn btn-primary' %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% elsif @user.organizer? && @user.organized_events.include?(@event) && @event.closed? %>
      <div class="description">
          <p> <%= @event.start_time.strftime("%a, %d %b %Y") %>
          <div class="title">
            <p><%= @event.title %></p>
          </div>
          <p><strong> by <%= @event.user.organizer_name %></strong></p>
          <div class="final-info">
          <div> Final results </div>
          <div class="final-title"><p> ATTENDEEES </p></div>
          <p><%= @event.tickets.select { |ticket| ticket.showup? }.size %> / <%= @event.tickets.size %> <strong>(<%= ((@event.tickets.select { |ticket| ticket.showup? }.size.to_f / @event.tickets.size)*100).round(1) %> %)</strong></p>
          <div class="final-title"><p> CASHBACK </p></div>
          <p><strong><%= @stake_earned %> € </strong></p>
          <!-- <p> number of people who canceled : <strong><%#= @event.tickets.select { |ticket| ticket.canceled? }.size %></strong></p> -->
          </div>
          </div>

    <% end %>

  <div class="bottom-line">
    <div class="description-and-share">
      <h4>Description</h4>
      <p><%= @event.description %></p>
      <h4>Share this event</h4>
        <div class="share-some">
          <%= social_share_button_tag(@event.title) %>
        </div>
      </div>
    </div>


    <div class="practical-info">
      <h4>Practical information</h4>
      <p><i class="far fa-clock pi-far"></i> <%= @event.start_time.strftime("%a, %d %b %Y") %> | <%= @event.start_time.to_s[-12..-8] %> <i class="fas fa-arrow-right"></i> <%= @event.end_time.to_s[-12..-8] %></p>
      <p><i class="fas fa-map-marker-alt pi-far" ></i> <a href="http://maps.google.com/maps/place/<%= URI::encode(@event.location) %>" target="_blank">  <%= @event.location %></a></p>
      <p><i class="fas fa-glass-martini-alt pi-far"></i> <%= @event.drink %>
        <% if @event.drink.capitalize == 'None' %>
          <i class="far fa-question-circle info-popup" data-toggle="tooltip" data-placement="top" title="The organizer does not provide free drinks to participants."></i></p>
        <% elsif @event.drink.capitalize == 'Free' %>
          <i class="far fa-question-circle info-popup" data-toggle="tooltip" data-placement="top" title="The organizer provides free drinks to participants."></i></p>
          <% elsif @event.drink.capitalize == 'Paid' %>
          <i class="far fa-question-circle info-popup" data-toggle="tooltip" data-placement="top" title="The organizer does not provide free drinks to participants, however it is possible to purchase drinks at the event."></i></p>
        <% end %>
      <p><i class="fas fa-utensils pi-far"></i> <%= @event.food %>
        <% if @event.food.capitalize == 'None' %>
          <i class="far fa-question-circle info-popup" data-toggle="tooltip" data-placement="top" title="The organizer does not provide free food to participants."></i></p>
        <% elsif @event.food.capitalize == 'Free' %>
          <i class="far fa-question-circle info-popup" data-toggle="tooltip" data-placement="top" title="The organizer provides free food to participants."></i></p>
          <% elsif @event.food.capitalize == 'Paid' %>
          <i class="far fa-question-circle info-popup" data-toggle="tooltip" data-placement="top" title="The organizer does not provide free food to participants, however it is possible to purchase food at the event."></i></p>
        <% end %>
      </p>
      <p><i class="fas fa-user-friends pi-far"></i> <%= @available_tickets %> / <%= @event.number_max_of_attendees %> Attendees </p>
    </div>
  </div>
</div>


<!-- app/views/offers/show.html.erb -->
<% content_for :meta_title, "#{@event.title} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @event.description %>
<% content_for :meta_image, cl_image_path(@event.photo.key) %>