config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :events do
    patch 'event_over', to: 'tickets#event_over', as: :event_over
    resources :tickets, only: %i[create index]
    patch 'tickets/:id/mark_as_cancelled', to: 'tickets#mark_as_cancelled', as: :mark_as_cancelled
    patch 'tickets/:id/mark_as_showed', to: 'tickets#mark_as_showed', as: :mark_as_showed
    patch 'tickets/:id/mark_as_attendee', to: 'tickets#mark_as_attendee', as: :mark_as_attendee
  end

  resources :tickets, only: %i[edit update show]

  resources :users, only: %i[new create show edit update] do
    resources :events, only: %i[new create]
    patch 'switch_to_organizer', to: 'users#switch_to_organizer', as: :switch_to_organizer
    patch 'switch_to_attendee', to: 'users#switch_to_attendee', as: :switch_to_attendee
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  get 'pages/sign_up_details', to: 'pages#sign_up_details', as: :sign_up_details
  get 'dashboard', to: 'dashboards#index', as: :dashboard
  root to: 'pages#home'
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :attending_event, class_name: "Event", foreign_key: :event_id
  belongs_to :user

  def attendee!
    self.status = 'Attending'
    save!
  end

  def attendee?
    status == 'Attending'
  end

  def showup!
    self.status = 'Showed up'
    save!
  end

  def showup?
    status == 'Showed up'
  end

  def cancel!
    self.status = 'Canceled'
    save!
  end

  def canceled?
    status == 'Canceled'
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
    before_action :set_ticket, only: [:show, :edit, :update, :mark_as_cancelled, :mark_as_showed, :mark_as_attendee]

  def index
    @event = Event.find(params[:event_id])
    @tickets = @event.tickets
      @search = params["search"]
    if @search.present?
      name = @search["name"]
      users = @event.users.where("first_name ILIKE ?", "%#{name}%").or(@event.users.where("last_name ILIKE ?", "%#{name}%"))
      @tickets = users.flat_map(&:tickets).select{|ticket|  ticket.event_id == @event.id}
    end

    @tickets = @tickets.sort_by { |ticket| ticket.user.last_name }
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user

    @existing_ticket = current_user.tickets.find_by(event_id: @ticket.event_id)
    if @existing_ticket.present?
      @ticket = @existing_ticket
    end
    @ticket.attendee!

    if @ticket.save
      redirect_to event_path(@ticket.attending_event)
    else
      render 'new'
    end
  end

  def show
  end

  def mark_as_showed
    @ticket.showup!
    redirect_to event_tickets_path(@ticket.event_id)
  end

  def mark_as_cancelled
    @ticket.cancel!
    @order = Order.find(@ticket.order_id)
    @order.cancel_payment
    @order.save!
    redirect_to event_path(@ticket.attending_event)
  end

  def mark_as_attendee
    @ticket.attendee!
    redirect_to event_tickets_path(@ticket.attending_event)
  end

  def event_over
    event = Event.find(params[:event_id])
    tickets = event.tickets
    event.close!
    event.save!
    tickets.each do |ticket|
      if ticket.showup?
        order = Order.find(ticket.order_id)
        order.cancel_payment
        order.save!
      elsif ticket.attendee?
        order = Order.find(ticket.order_id)
        order.collect_payment
        order.save!
      end
    end
    redirect_to event_path(event)
  end

  private

  def ticket_params
    params.permit(:status, :user_id, :event_id, :order_id)
  end

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end
end

app/views/tickets/_search_ticket.html.erb
<div class="container my-5 search-form">
  <div class="title">
    <h3>Search for tickets</h3>
  </div>
  <div class="hz">
    <%= simple_form_for :search, url: event_tickets_path(@event), method: "GET", html: { class: 'form-inline' } do |f| %>
        <%= f.input :name, input_html: {value: ""}, required: false, label: false %>
        <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tickets/index.html.erb
<div class="container">
    <h1><%= @event.title %></h1>
    <p><%= @event.start_time.strftime("%a, %d %b %Y") %></p>
    <h2>Attendees - <%= @event.tickets.select { |ticket| ticket.showup? }.count %> / <%= @event.tickets.size %></h2>
    <%= render "search_ticket" %>
    <div class="row">
    <% @tickets.each do |ticket| %>
      <div class="user-event-status">
        <div class="status">
          <% if ticket.status.nil? %>
            <i class="fas fa-check"></i>
            <i class="fas fa-times"></i>
          <% else %>
            <% if !ticket.showup? %>
              <%= link_to event_mark_as_showed_path(@event, ticket), method: :patch do %>
              <i class="fas fa-check" style='color: lightgrey !important; font-size: 2vw;'></i>
            <% end %>
            <i class="fas fa-times" style = 'color: red; font-size: 2vw;'></i>
          <% elsif ticket.showup? %>
            <i class="fas fa-check" style="color = green; font-size: 2vw;"></i>
              <%= link_to event_mark_as_attendee_path(@event, ticket), method: :patch do %>
            <i class="fas fa-times" style='color: lightgrey !important; font-size: 2vw;'></i>
          <% end %>
          <% end %>
          <% end %>
        </div>
        <div class="users-details">
          <%= ticket.user.last_name %> <%= ticket.user.first_name %>
        </div>
      </div>
    <% end  %>
    </div>
    <%= link_to 'Back to event', event_path(@event), class: "btn btn-flat" %>
    <% if !@event.closed? && @event.end_time > DateTime.current.to_date %>
      <%= link_to 'Finalize event', event_event_over_path(@event), method: :patch, class: 'btn btn-primary', data: { confirm: 'By finalizing the event, you confirm the attendance list. Finalizing the event is irreversible.' } %>
    <% end %>
  </div>
</div>