config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :events do
    patch 'event_over', to: 'tickets#event_over', as: :event_over
    resources :tickets, only: %i[create index]
    patch 'tickets/:id/mark_as_cancelled', to: 'tickets#mark_as_cancelled', as: :mark_as_cancelled
    patch 'tickets/:id/mark_as_showed', to: 'tickets#mark_as_showed', as: :mark_as_showed
    patch 'tickets/:id/mark_as_attendee', to: 'tickets#mark_as_attendee', as: :mark_as_attendee
  end

  resources :tickets, only: %i[edit update show]

  resources :users, only: %i[new create show edit update] do
    resources :events, only: %i[new create]
    patch 'switch_to_organizer', to: 'users#switch_to_organizer', as: :switch_to_organizer
    patch 'switch_to_attendee', to: 'users#switch_to_attendee', as: :switch_to_attendee
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  get 'pages/sign_up_details', to: 'pages#sign_up_details', as: :sign_up_details
  get 'dashboard', to: 'dashboards#index', as: :dashboard
  root to: 'pages#home'
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @user = current_user

    if @user.organizer?
      @future_events = @user.organized_events.select {|ev| ev.start_time.future? }
      @past_events = @user.organized_events.select {|ev| ev.start_time.past? }
    elsif @user.attendee?
      @future_events = @user.attending_events.select {|ev| ev.start_time.future? }
      @past_events = @user.attending_events.select {|ev| ev.start_time.past? }
    end
  end

  def upcoming_events
    @event.future?
  end

  def past_events
    @event.past?
  end

end

app/views/dashboards/index.html.erb
<div class="container">

    <div class="bm-5">
    <div class="same-line">
      <div class="title">
        <h3>Upcoming events</h3>
      </div>
        <% if current_user.organizer? %>
          <div class="button-right">
            <%= link_to "Create a new event", new_event_path, class: 'btn btn-primary' %>
          </div>
        <% end %>
    </div>
    </div>
    <div class="row">
    <% if @user.attendee? %>
      <% if @future_events.size > 0 %>
        <% @future_events.each do |event|  %>
        <div class="home-cards col-sm-4">
          <%= render "./events/event_card", event: event if (@user.attending_events.include?(event) && !event.tickets.where(user: @user)[0].canceled?) %>
        </div>
        <% end %>
      <% else %>
        <br><br>
        <h5><i class="fas fa-surprise"></i> You don't have any upcoming events, <strong><%= link_to 'find', events_path %></strong> some !</h5>
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
      <% end %>
    </div>
      <div class="mb-5">
        <div class="container">
        <h3> Past Events </h3>
      </div>
    <div class="row">
      <% @past_events.each do |event| %>
      <div class="home-cards col-sm-4">
        <%= render "./events/event_card", event: event if (@user.attending_events.include?(event) && !event.tickets.where(user: @user)[0].canceled?)  %>
      </div>
      <% end %>
    <% elsif @user.organizer? %>
      <% if @future_events.size > 0 %>
        <% @future_events.each do |event|  %>
        <div class="home-cards col-sm-4">
          <%= render "./events/event_card", event: event if @user.organized_events.include?(event) %>
        </div>
        <% end %>
      <% else %>
        <br><br>
        <h5><i class="fas fa-surprise"></i> You don't have any upcoming events, <strong><%= link_to 'organize', new_event_path %></strong> some !</h5>
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
      <% end %>
    </div>
      <div class="mb-5">
        <h3> Past Events </h3>
      </div>
    <div class="row">
      <% @past_events.each do |event| %>
      <div class="home-cards col-sm-4">
        <%= render "./events/event_card", event: event if @user.organized_events.include?(event)  %>
       </div>
      <% end %>
    <% end %>
    </div>
  <div class="mb-5">
  </div>
</div>